# Archivo de configuración para SonarQube
sonar.projectKey=parqueadero-ia
sonar.projectName=Parqueadero IA
sonar.projectVersion=1.0

# Fuentes y pruebas
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.13

# Cobertura
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/migrations/**,**/static/**,**/templates/**

# Reglas de calidad
sonar.qualitygate.wait=true